name: Go Test

on:
  # Trigger on pull requests open and sync (new commits, etc..) events
  pull_request:
    types: [opened, synchronize]
    branches: [main]
    paths-ignore: ["README.md"] # Ignore changes to the README

# Cancel any previous runs in progress if new ones come in (Avoid excessive build queue)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Run tests
        run: make test
